// AUTO-GENERATED by scripts/gen-demo-sample.mjs — DO NOT EDIT BY HAND.
// A sample AXR step receipt signed with a disposable Ed25519 key, so the
// /axr/start "Seal & Tamper" demo runs a real signature check (not a fake).
// Regenerate with: node scripts/gen-demo-sample.mjs

export const SAMPLE_PUBKEY_PEM = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAMQJ48bLR50VwO74xi0iMC28FioDyRzf0fCxmjhTScvg=\n-----END PUBLIC KEY-----";

export const SAMPLE_RECEIPT = {
  "axr_version": "0.2",
  "receipt_type": "step",
  "receipt_id": "rcpt_demo_5f3a9c",
  "workflow_receipt_id": "wf_demo_5f3a9c",
  "sequence": 5,
  "timestamp": "2026-06-26T09:14:22Z",
  "agent_id": "axr:agent:eco-clean:v5.2",
  "step": {
    "node_name": "Create Booking",
    "node_type": "n8n-nodes-base.googleCalendar",
    "logic_version": "5.2 HU",
    "deterministic": true
  },
  "io": {
    "input_summary": {
      "customer": "A. Nagy",
      "service": "Carpet clean",
      "date": "2026-07-02",
      "price": "38000"
    },
    "decision": "BOOKING_CONFIRMED"
  },
  "previous_receipt_hash": "sha256:5c10e8a1d9f3b27744a0c6e1b8f209d4a17c3e55b9026d8841fb73ac9e120d9f3",
  "signature": "scT2Nf674h6t5aS+Wg+7HBA90JcggMkOtUuZcDm3UK3wT+71ny4mRrHCm7rUeAaryk8SE59jKQ8T/fLvzG7bBg=="
} as const;
